packages:
  - block
  - kind
  - model
  - software/antifold/software
  - software/antifold/workflow
  - software/developability/software
  - software/developability/workflow
  - test
  - ui
  - workflow
catalog:
  "@platforma-sdk/model": 1.83.9
  "@platforma-sdk/ui-vue": 1.83.13
  "@platforma-sdk/workflow-tengo": 6.10.0
  "@platforma-sdk/test": 1.83.16
  "@platforma-sdk/block-tools": 2.15.1
  "@platforma-sdk/tengo-builder": 4.0.26
  "@platforma-sdk/package-builder": 3.16.0
  "@milaboratories/ts-builder": 1.7.2
  "@milaboratories/ts-configs": 1.4.0
  "@milaboratories/structure-viewer": 0.3.1
  "@milaboratories/multi-sequence-alignment": 1.47.18
  turbo: ~2.8.11
  shx: ~0.4.0
  "@changesets/cli": ~2.29.8
  vitest: ~4.0.18
  typescript: ~5.9.3
  "@platforma-open/milaboratories.runenv-python-3": 1.8.2
  vue: 3.5.24
  "@milaboratories/helpers": 1.14.5
  ag-grid-enterprise: ~34.1.2
  ag-grid-vue3: ~34.1.2
  "@platforma-sdk/block-kind": 1.1.0
